# -*- coding: utf-8 -*-
"""Titanic Exploratory Data Analysis (EDA) Using Python

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PqWmW3ljawpgi3o2uY-_ApJAcSB_3N4f

Import Libraries
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

"""Upload Dataset"""

from google.colab import files

uploaded = files.upload()

"""Load Dataset"""

df = pd.read_csv("train.csv")

df.head()

"""Understand Dataset"""

df.info()

"""Check Missing Values"""

df.isnull().sum()

"""Fill Missing Age Values"""

df["Age"] = df["Age"].fillna(df["Age"].mean())

"""Fill Missing Embarked Values"""

df["Embarked"] = df["Embarked"].fillna(df["Embarked"].mode()[0])

"""Drop Cabin Column"""

df.drop(columns=["Cabin"], inplace=True)

"""Verify Cleaning"""

df.isnull().sum()

"""Create Age Groups"""

df["AgeGroup"] = pd.cut(
    df["Age"],
    bins=[0, 12, 18, 35, 60, 80],
    labels=["Child", "Teen", "YoungAdult", "Adult", "Senior"]
)

"""Check Age Groups"""

df[["Age", "AgeGroup"]].head()

"""Survival Rate by Age Group"""

age_survival = df.groupby("AgeGroup")["Survived"].mean() * 100

print(age_survival.round(2))

"""Visualization – Age Group Survival"""

sns.barplot(
    x="AgeGroup",
    y="Survived",
    data=df
)

plt.title("Survival Rate by Age Group")
plt.show()

"""Survival Rate by Embarkation Port"""

port_survival = df.groupby("Embarked")["Survived"].mean() * 100

print(port_survival.round(2))

"""Visualization – Embarkation Port"""

sns.barplot(
    x="Embarked",
    y="Survived",
    data=df
)

plt.title("Survival Rate by Embarkation Port")
plt.show()

"""Create Family Size Feature"""

df["FamilySize"] = df["SibSp"] + df["Parch"]

"""Survival Rate by Family Size"""

df[["SibSp", "Parch", "FamilySize"]].head()

"""Visualization – Family Size"""

family_survival = df.groupby("FamilySize")["Survived"].mean() * 100

print(family_survival.round(2))

"""Histogram of Age Distribution"""

sns.barplot(
    x="FamilySize",
    y="Survived",
    data=df
)

plt.title("Survival Rate by Family Size")
plt.show()

"""Histogram of Age Distribution"""

plt.hist(df["Age"], bins=20)

plt.title("Age Distribution of Passengers")
plt.xlabel("Age")
plt.ylabel("Count")

plt.show()

"""Correlation Heatmap"""

df["Sex"] = df["Sex"].map({
    "male": 0,
    "female": 1
})

"""Create Correlation Matrix"""

corr = df.select_dtypes(include="number").corr()

corr

"""Plot Heatmap"""

plt.figure(figsize=(10, 6))

sns.heatmap(
    corr,
    annot=True,
    cmap="coolwarm"
)

plt.title("Correlation Heatmap")

plt.show()

"""Conclusion

1. Survival rates differed across age groups.
2. Embarkation port influenced survival probability.
3. Family size affected survival chances.
4. Most passengers were between 20 and 40 years old.
5. Gender and passenger class showed strong relationships with survival.
6. Data visualization helped reveal hidden patterns in the Titanic dataset.
"""

